{% set version = "1.0.2" %}

package:
  name: arrow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arrow/arrow-{{ version }}.tar.gz
  sha256: 5df8e632e9158c48f42f68a742068bcfc1c0181cbe7543e4cda6089bb287a305

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil >=2.7.0
    - typing_extensions

test:
  source_files:
    - tests
  requires:
    - dateparser
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - pytz
    - simplejson
  commands:
    - pip check
    - cd tests && pytest --cov arrow -k "not parse_tz_name_zzz"

about:
  home: https://github.com/crsmithdev/arrow
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Better dates & times for Python
  description: |
    Arrow is a Python library that offers a sensible, human-friendly approach to
    creating, manipulating, formatting and converting dates, times, and timestamps.
    It implements and updates the datetime type, plugging gaps in functionality,
    and provides an intelligent module API that supports many common creation
    scenarios. Simply put, it helps you work with dates and times with fewer
    imports and a lot less code.
  dev_url: https://github.com/crsmithdev/arrow
  doc_url: https://arrow.readthedocs.io
  doc_source_url: https://github.com/crsmithdev/arrow/tree/master/docs

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
