{% set version = "0.12.1" %}

package:
  name: arrow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arrow/arrow-{{ version }}.tar.gz
  sha256: a558d3b7b6ce7ffc74206a86c147052de23d3d4ef0e17c210dd478c53575c4cd

build:
  number: 1002
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - backports.functools_lru_cache  # [py2k]

test:
  source_files:
    - tests
  requires:
    - nose
    - chai
    - simplejson
  commands:
    - nosetests

about:
  home: https://github.com/crsmithdev/arrow
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Better dates & times for Python.'
  description: |
    Arrow is a Python library that offers a sensible, human-friendly approach to
    creating, manipulating, formatting and converting dates, times, and timestamps.
    It implements and updates the datetime type, plugging gaps in functionality,
    and provides an intelligent module API that supports many common creation
    scenarios. Simply put, it helps you work with dates and times with fewer
    imports and a lot less code.
  dev_url: https://github.com/crsmithdev/arrow
  doc_url: http://arrow.readthedocs.org

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
