{% set version = "0.10.0" %}
{% set gh_org = "crsmithdev" %}

package:
  name: arrow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arrow/arrow-{{ version }}.tar.gz
  sha256: 805906f09445afc1f0fc80187db8fe07670e3b25cdafa09b8d8ac264a8c0c722

build:
  number: 1
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - python-dateutil

test:
  source_files:
    - tests
  requires:
    - nose
    - chai
    - simplejson
  commands:
    - nosetests

about:
  home: https://github.com/crsmithdev/arrow
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Better dates & times for Python.'
  description: |
    Arrow is a Python library that offers a sensible, human-friendly approach to
    creating, manipulating, formatting and converting dates, times, and timestamps.
    It implements and updates the datetime type, plugging gaps in functionality,
    and provides an intelligent module API that supports many common creation
    scenarios. Simply put, it helps you work with dates and times with fewer
    imports and a lot less code.
  dev_url: https://github.com/crsmithdev/arrow
  doc_url: http://arrow.readthedocs.org

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
