travis:
  secure:
    BINSTAR_TOKEN: NPk3tQVBuxz5ACrQAFdTSLXgkWHfWDaYOPKeDTphlIkAqm5dtqrNu14Vy1C7XRUg6HmOd9r2j/y3yfUPYbGsTbfn829aH0Vhhx1F5zpfGbW2STuQRHo3s6GbntteBgOVObQeMVJXQgN1DAcrti1dUdMJOLYA6MsjbwmFU3u5mZf/ZRJiL6Gyv5cMdQvoItVNY33RQw/3tpw7mwlBatSrjM6oOMlee9lUGQcTZiXvDmw4WxLYEtqwz1z0S7RwIOUmGBHqSzN6jYntXbN+3mGc0y9LNInbhJc7WHMzV8K1vXxP6a7yc3O898rXYAvAhDZQkEVnBhVaE7m9Ns8JvcYaMlhiqKLQn8lFkh2bL/pur8IGHmaMdQENDizjAZGhUgR8NuFUaQmSvbmY6HodG3yLRa1ZMUWIHtuvIeHBAPVXWQ0+xpaF7viffe2x8PyGlm7DAS68g9jwaehAXLoA511S6c2vsROVwN1kZpdLUiHRBqKckxTtqFKjIgfmEu325AtIWP8nbsZwD/D1mgwfYg3I3tQS+BRqysuRhVVZMMdT3CW7tB/FmjKQoTY41N+G6serMd29ZjEhi7dICgHvhlLW8blXbHlCxA+MpjPONwzbNQAWiVnLhoAOTxc8elpisDJQWCSXe6YgPRSNPPTidgGRgCZ7eloyDwwawjc/y5iBUOA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
